init: start sprint 4
ClevertecFrontendLab/BukavnyovaN pull request #4
Opened 2024-03-17 21:38 UTC by BukavnyovaN

2024-03-17 21:40 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 75%.
Общее количество тестов: 4.
Количество непройденных тестов: 1.

2024-03-17 21:52 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 75%.
Общее количество тестов: 4.
Количество непройденных тестов: 1.

2024-03-17 22:19 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 75%.
Общее количество тестов: 4.
Количество непройденных тестов: 1.

2024-03-17 22:28 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 75%.
Общее количество тестов: 4.
Количество непройденных тестов: 1.

2024-03-17 22:32 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 75%.
Общее количество тестов: 4.
Количество непройденных тестов: 1.

2024-03-17 22:42 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 75%.
Общее количество тестов: 4.
Количество непройденных тестов: 1.

2024-03-18 05:05 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 75%.
Общее количество тестов: 4.
Количество непройденных тестов: 1.

2024-03-18 05:23 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 75%.
Общее количество тестов: 4.
Количество непройденных тестов: 1.

2024-03-18 05:26 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 0%.
Общее количество тестов: 1.
Количество непройденных тестов: 1.

2024-03-18 05:30 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 0%.
Общее количество тестов: 4.
Количество непройденных тестов: 4.

2024-03-18 05:37 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 50%.
Общее количество тестов: 4.
Количество непройденных тестов: 2.

2024-03-18 05:40 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 75%.
Общее количество тестов: 4.
Количество непройденных тестов: 1.

2024-03-18 05:43 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 75%.
Общее количество тестов: 4.
Количество непройденных тестов: 1.

2024-03-18 05:52 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 75%.
Общее количество тестов: 4.
Количество непройденных тестов: 1.

2024-03-18 05:57 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 75%.
Общее количество тестов: 4.
Количество непройденных тестов: 1.

2024-03-18 06:00 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 75%.
Общее количество тестов: 4.
Количество непройденных тестов: 1.

2024-03-18 06:14 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 75%.
Общее количество тестов: 4.
Количество непройденных тестов: 1.

2024-03-18 06:30 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 75%.
Общее количество тестов: 4.
Количество непройденных тестов: 1.

2024-03-18 06:38 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 75%.
Общее количество тестов: 4.
Количество непройденных тестов: 1.

2024-03-18 06:49 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 75%.
Общее количество тестов: 4.
Количество непройденных тестов: 1.

2024-03-18 06:55 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 75%.
Общее количество тестов: 4.
Количество непройденных тестов: 1.

2024-03-18 07:09 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 75%.
Общее количество тестов: 4.
Количество непройденных тестов: 1.

2024-03-18 07:12 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 75%.
Общее количество тестов: 4.
Количество непройденных тестов: 1.

2024-03-18 07:17 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 75%.
Общее количество тестов: 4.
Количество непройденных тестов: 1.

2024-03-18 07:24 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 75%.
Общее количество тестов: 4.
Количество непройденных тестов: 1.

2024-03-18 07:31 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 75%.
Общее количество тестов: 4.
Количество непройденных тестов: 1.

2024-03-18 07:40 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 75%.
Общее количество тестов: 4.
Количество непройденных тестов: 1.

2024-03-18 07:43 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 75%.
Общее количество тестов: 4.
Количество непройденных тестов: 1.

2024-03-18 07:54 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 75%.
Общее количество тестов: 4.
Количество непройденных тестов: 1.

2024-03-18 08:02 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 75%.
Общее количество тестов: 4.
Количество непройденных тестов: 1.

2024-03-18 08:08 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 75%.
Общее количество тестов: 4.
Количество непройденных тестов: 1.

2024-03-18 08:18 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 75%.
Общее количество тестов: 4.
Количество непройденных тестов: 1.

2024-03-18 09:17 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 25%.
Общее количество тестов: 4.
Количество непройденных тестов: 3.

2024-03-18 10:49 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 75%.
Общее количество тестов: 4.
Количество непройденных тестов: 1.

2024-03-18 10:53 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 75%.
Общее количество тестов: 4.
Количество непройденных тестов: 1.

2024-03-18 10:58 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 75%.
Общее количество тестов: 4.
Количество непройденных тестов: 1.

2024-03-18 11:12 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 75%.
Общее количество тестов: 4.
Количество непройденных тестов: 1.

2024-03-18 15:00 UTC, SergeyGlazun requested changes
![image](https://github.com/ClevertecFrontendLab/BukavnyovaN/assets/70904466/36d5d384-4d3b-4ea7-85c8-dc80c14fb565)
тут над будет консольку с коментами убрать

2024-03-18 15:02 UTC, SergeyGlazun commented
![image](https://github.com/ClevertecFrontendLab/BukavnyovaN/assets/70904466/72f07376-a01c-48de-8e37-bd1c41230c47)
тут можно вынести в константу

2024-03-18 16:14 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 4.
Количество непройденных тестов: 0.
***
**calendar-page_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/BukavnyovaN/1710778499/calendar-page_1440x900.png)
***
**create-new-training-1_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/BukavnyovaN/1710778499/create-new-training-1_1440x900.png)
***
**create-new-training-2_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/BukavnyovaN/1710778499/create-new-training-2_1440x900.png)
***
**create-new-training-3_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/BukavnyovaN/1710778499/create-new-training-3_1440x900.png)
***
**empty-calendar-page_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/BukavnyovaN/1710778499/empty-calendar-page_1440x900.png)
***
**get-training-error_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/BukavnyovaN/1710778499/get-training-error_1440x900.png)
***
**get-training-list-error_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/BukavnyovaN/1710778499/get-training-list-error_1440x900.png)
***
**update-future-trainings-1_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/BukavnyovaN/1710778499/update-future-trainings-1_833x900.png)
***
**update-future-trainings-2_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/BukavnyovaN/1710778499/update-future-trainings-2_833x900.png)
***
**update-future-trainings-3.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/BukavnyovaN/1710778499/update-future-trainings-3.png)
***
**update-past-trainings-1_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/BukavnyovaN/1710778499/update-past-trainings-1_360x740.png)
***
**update-past-trainings-2.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/BukavnyovaN/1710778499/update-past-trainings-2.png)
***
**update-past-trainings-3_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/BukavnyovaN/1710778499/update-past-trainings-3_360x740.png)

2024-03-18 17:20 UTC, SergeyGlazun approved these changes

2024-03-18 17:27 UTC, ValadzkoAliaksei commented on package.json
> +    "dayjs": "^1.11.10",
и dayjs и moment может выберем давай что-то одно?)

2024-03-18 17:27 UTC, ValadzkoAliaksei commented on src/components/calendar-exercises-modal/calendar-exercises-modal.css
> +
предлагаю файлик удалить)

2024-03-18 17:27 UTC, ValadzkoAliaksei commented on src/components/calendar-exercises-modal/calendar-exercises-modal.tsx
> +                                           setIsEditTraining} : CalendarExercisesModalProps) => {
а точно линтеры включены?)

2024-03-18 17:53 UTC, ValadzkoAliaksei requested changes
Комменты выше

2024-03-18 19:41 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 4.
Количество непройденных тестов: 0.
***
**calendar-page_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/BukavnyovaN/1710790887/calendar-page_1440x900.png)
***
**create-new-training-1_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/BukavnyovaN/1710790887/create-new-training-1_1440x900.png)
***
**create-new-training-2_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/BukavnyovaN/1710790887/create-new-training-2_1440x900.png)
***
**create-new-training-3_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/BukavnyovaN/1710790887/create-new-training-3_1440x900.png)
***
**empty-calendar-page_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/BukavnyovaN/1710790887/empty-calendar-page_1440x900.png)
***
**get-training-error_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/BukavnyovaN/1710790887/get-training-error_1440x900.png)
***
**get-training-list-error_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/BukavnyovaN/1710790887/get-training-list-error_1440x900.png)
***
**update-future-trainings-1_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/BukavnyovaN/1710790887/update-future-trainings-1_833x900.png)
***
**update-future-trainings-2_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/BukavnyovaN/1710790887/update-future-trainings-2_833x900.png)
***
**update-future-trainings-3.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/BukavnyovaN/1710790887/update-future-trainings-3.png)
***
**update-past-trainings-1_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/BukavnyovaN/1710790887/update-past-trainings-1_360x740.png)
***
**update-past-trainings-2.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/BukavnyovaN/1710790887/update-past-trainings-2.png)
***
**update-past-trainings-3_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/BukavnyovaN/1710790887/update-past-trainings-3_360x740.png)

2024-03-18 19:49 UTC, merged