Sprint 5
ClevertecFrontendLab/BukavnyovaN pull request #5
Opened 2024-03-26 12:10 UTC by BukavnyovaN

2024-03-26 12:13 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 5.
Количество непройденных тестов: 0.
***
**buy-tariff-success_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/BukavnyovaN/1711455182/buy-tariff-success_1440x900.png)
***
**default-profile-page_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/BukavnyovaN/1711455182/default-profile-page_1440x900.png)
***
**default-settings-page_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/BukavnyovaN/1711455182/default-settings-page_1440x900.png)
***
**feedbacks with photo_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/BukavnyovaN/1711455182/feedbacks%20with%20photo_1440x900.png)
***
**modal-big-photo_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/BukavnyovaN/1711455182/modal-big-photo_1440x900.png)
***
**profile-modal-error_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/BukavnyovaN/1711455182/profile-modal-error_1440x900.png)
***
**profile-modal-success_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/BukavnyovaN/1711455182/profile-modal-success_1440x900.png)
***
**settings-page-with-sider_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/BukavnyovaN/1711455182/settings-page-with-sider_360x740.png)
***
**settings-pro-cards_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/BukavnyovaN/1711455182/settings-pro-cards_360x740.png)
***
**settings-sider-pro_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/BukavnyovaN/1711455182/settings-sider-pro_833x900.png)

2024-03-26 19:22 UTC, byshlata requested changes
Замечания по коду

2024-03-26 19:22 UTC, byshlata commented on src/components/profile-form/credentials-form-item/credentials-form-item.tsx
> +interface CredentialsFormProps {
interface меняем на типы

2024-03-26 19:22 UTC, byshlata commented on src/components/profile-form/personal-info-form-item/personal-info-form-item.css
> +.profile-form__personal-info-inputs > div > div > div > div > div > .ant-input {
прям жестко ты

2024-03-26 19:22 UTC, byshlata commented on src/components/profile-form/personal-info-form-item/personal-info-form-item.tsx
> +interface PersonalInfoFormProps {
?

2024-03-26 19:22 UTC, byshlata commented on src/components/profile-form/personal-info-form-item/personal-info-form-item.tsx
> +    return (
return можно убрать

2024-03-26 19:22 UTC, byshlata commented on src/components/profile-form/profile-form.tsx
> +interface FormState {
type FormState = Partial\<{.......}>

2024-03-27 05:34 UTC, VitalyHanchar commented on package.json
>    },
Имя Фамилия в одну строку.
![image](https://github.com/ClevertecFrontendLab/BukavnyovaN/assets/122732222/5002eb58-1adc-48c2-bb82-1271ddb230ea)

2024-03-27 05:55 UTC, VitalyHanchar requested changes
-

2024-03-27 11:52 UTC, BukavnyovaN commented on package.json
>    },
В макете по странице отзывов имя фимиля начинались с разных строк. Или этот макет уже не актуален? 🥺

![capture_20240327144943769](https://github.com/ClevertecFrontendLab/BukavnyovaN/assets/96077008/053a07b1-ceab-4d93-8d43-d5e0fe0854e6)

2024-03-27 12:15 UTC, VitalyHanchar commented on package.json
>    },
Ошибся, исправлять не надо.

2024-03-28 08:03 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 5.
Количество непройденных тестов: 0.
***
**buy-tariff-success_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/BukavnyovaN/1711613030/buy-tariff-success_1440x900.png)
***
**default-profile-page_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/BukavnyovaN/1711613030/default-profile-page_1440x900.png)
***
**default-settings-page_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/BukavnyovaN/1711613030/default-settings-page_1440x900.png)
***
**feedbacks with photo_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/BukavnyovaN/1711613030/feedbacks%20with%20photo_1440x900.png)
***
**modal-big-photo_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/BukavnyovaN/1711613030/modal-big-photo_1440x900.png)
***
**profile-modal-error_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/BukavnyovaN/1711613030/profile-modal-error_1440x900.png)
***
**profile-modal-success_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/BukavnyovaN/1711613030/profile-modal-success_1440x900.png)
***
**settings-page-with-sider_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/BukavnyovaN/1711613030/settings-page-with-sider_360x740.png)
***
**settings-pro-cards_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/BukavnyovaN/1711613030/settings-pro-cards_360x740.png)
***
**settings-sider-pro_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/BukavnyovaN/1711613030/settings-sider-pro_833x900.png)

2024-03-28 08:18 UTC, byshlata approved these changes

2024-03-28 08:23 UTC, merged